pipeline {
    agent any

    environment {
        IMAGE_NAME = "emoji-app" // docker-compose.yml ile aynı olsun
        CONTAINER_NAME = "emoji-app-container"
        PORT = "4646"       // Dış port
        APP_PORT = "4646"   // server.js içindeki port (3000'i 4646 yaptık)
        REPO_URL = "git@github.com:elcinaltnz/elc.git"
        BRANCH = "main"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Clone Repository') {
            steps {
                git branch: "${BRANCH}",
                    url: "${REPO_URL}"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build -t ${IMAGE_NAME}:latest .
                """
            }
        }

        stage('Stop & Remove Old Container') {
            steps {
                sh """
                docker rm -f ${CONTAINER_NAME} || true
                """
            }
        }

        stage('Run New Container') {
            steps {
                sh """
                docker run -d \
                -p ${PORT}:${APP_PORT} \
                --name ${CONTAINER_NAME} \
                ${IMAGE_NAME}:latest
                """
            }
        }

        stage('Show Running Containers') {
            steps {
                sh "docker ps"
            }
        }
    }

    post {
        success {
            echo "✅ Deployment başarılı!"
        }
        failure {
            echo "❌ Pipeline hata verdi!"
        }
    }
}
