pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/KULLANICI_ADI/REPO_ADI.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ci-test .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 4646:3000 ci-test'
            }
        }
    }
}
